### ISSUE TITLE
upload_file API end-point responds with an incorrect error response.

### ISSUE THREAD

**Issue by Garee** [Doist/todoist-api#5]
This is an API issue rather than a documentation issue but I figured here was a good place to report it.

In the [error section](https://developer.todoist.com/#errors) of the documentation it says:

> In any case, a JSON object is always returned.

However, when I try to upload a file that doesn't exist the HTTP response status is 200 and the body isn't valid JSON:

```python
$ python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> response = requests.post('https://api.todoist.com/API/v6/register',
...                          params={'email': 'example_email_54321@gmail.com',
...                                  'full_name': 'Example User',
...                                  'password': 'password'})
>>> api_token = response.json()['api_token']
>>> response = requests.post('https://api.todoist.com/API/v6/upload_file',
...                          params={'token': api_token, 'file_name': None})
>>> response.status_code
200
>>> response.text
'error_codeerror'
>>> response.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files (x86)\Python\342\lib\site-packages\requests\models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "c:\Program Files (x86)\Python\342\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Program Files (x86)\Python\342\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Program Files (x86)\Python\342\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

I believe this should be responding with a status code of 400 and a body similar to:

```
{"error_code": error_code, "error": error_string}
```

**Comment by eleftherios-c** [comment]
Already fixed.

In this scenario the following is returned:

`{"error_tag":"UPLOAD_FAILED","error_code":15,"error_extra":{},"error":"Failed to upload file"}`
