### ISSUE TITLE
delete_user API end-point responds with an error even if the user is succesfully deleted

### ISSUE THREAD

**Issue by Garee** [Doist/todoist-api#6]
The ```delete_user``` api end-point is responding with a HTTP 400 status code and a non-json body even if the user is successfully deleted.

```python
$ python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on w
in32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> response = requests.get('https://api.todoist.com/API/v6/login',
...                         params={'email': 'example_email_54321@gmail.com',
...                                 'password': 'password'})
>>> response.status_code
200
>>> response = requests.post('https://api.todoist.com/API/v6/delete_user',
...                          params={'token': response.json()['api_token'],
...                                  'current_password': 'password'})
>>> response.status_code
400
>>> response.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files (x86)\Python\342\lib\site-packages\requests\models.py", line 802,
 in json
    return json.loads(self.text, **kwargs)
  File "c:\Program Files (x86)\Python\342\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Program Files (x86)\Python\342\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Program Files (x86)\Python\342\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
>>> response.text
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>400 Bad Request</title>\n
<h1>Bad Request</h1>\n<p>Invalid or missing CSRF token</p>\n'
>>> response = requests.get('https://api.todoist.com/API/v6/login',
...                         params={'email': 'example_email_54321@gmail.com',
...                                 'password': 'password'})
>>> response.status_code
400
>>> response.json()
{'error': 'Wrong email or password', 'error_code': 9}
```

Even if it did fail I expected the body to be a JSON message such as:

```
{"error_code": error_code, "error": error_string}
```

**Comment by eleftherios-c** [comment]
Already fixed.

This is returned on an incorrect password:

`{ "error_extra" : {}, "error_tag" : "INVALID_PASSWORD", "error_code" : 112, "error" : "Invalid password" }`

And this on an incorrect token:

`{"error_tag":"AUTH_INVALID_TOKEN","error_code":401,"error_extra":{"access_type":"access_token"},"error":"Invalid token"}`
